
spring:
  application:
    name: FootballManagement

  datasource:
    url: jdbc:postgresql://localhost:5435/learn_db
    username: ferid
    password: ferid1234

  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080

